// distsexo.js
// 
exports.genDistSexo = function(lista,data){
    var pagHTML= `
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8"/>
        <title>About people...</title>
         <link rel="stylesheet" href="w3.css"/> 
    </head>

    <body>
         <div class="w3-card-4">

            <header class="w3-container w3-teal">
                <h1>Distribuição pas pessoas por sexo</h1>
            </header>

            <div class="w3-container">

                <table class="w3-table-all"> 
                    <tr>
                      <th>Masculino</th>
                      <th>Feminino</th>
                    </tr> 

                    <tr>`

    var m = 0
    var f = 0
    for  (let i = 0;i < lista.length; i++) {
        if (lista[i].sexo == "feminino") {
            f += 1;
        }
        if (lista[i].sexo == "masculino") {
            m += 1;
        }
    }

    pagHTML += 
    `
                        <td>${m}<td>
                        <td>${f}</td>
                    </tr>


                </table>

                <button class="w3-button w3-hover-yellow"><a href="/sexomas"    >Lista de Masculinos</a></button>
                <button class="w3-button w3-hover-red">   <a href="/sexofem"    >Lista de Femininos</a></button>


            </div>

            <footer class="w3-container w3-teal">
                <h5>Generated by pessoas-server:${data}</h5>
            </footer>

        </div> 
    </body>
</html>`

    return pagHTML
}
